add option to select file category for organization
Details:
- Adds a new option `-m` to specify the file category.
- The category is based on common file types, for example:
  `.docx`, `.odt`, and `.pdf` are categorized as documents.

Benefits:
- Provides flexibility by allowing users to select which file categories to organize.

diff --git a/bin/organize b/bin/organize
--- a/bin/organize
+++ b/bin/organize
@@ -144,14 +144,39 @@ function organize_so_images() {
 
 function main() {
     clear
-    organize_office_documents
-    organize_images
-    organize_compressed_files
-    organize_uncategorized_files
-    organize_apps
-    organize_audios
-    organize_videos
-    organize_so_images
+    case "$1" in
+        docs) organize_office_documents ;;
+        images) organize_images ;;
+        comp_files) organize_compressed_files ;;
+        uncat_files) organize_uncategorized_files ;;
+        apps) organize_apps ;;
+        audios) organize_audios ;;
+        videos) organize_videos ;;
+        isos) organize_so_images ;;
+        *)
+            if [[ ! (-z "$1") ]]; then
+                echo "Unrecognized option: $1"
+                exit 1
+            fi
+            organize_office_documents
+            organize_images
+            organize_compressed_files
+            organize_uncategorized_files
+            organize_apps
+            organize_audios
+            organize_videos
+            organize_so_images
+    esac
 }
 
-main
+while getopts ":m:" opt; do
+    # shellcheck disable=SC2154
+    case "$opt" in
+        m)
+            main "$2"
+            shift 2
+            ;;
+        *)
+            echo "Invalid option: ${opt}!"
+    esac
+done
